services:
  web:
    build: .
    ports:
      - "8000:8000"
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
  db:
    image: postgres:14-alpine3.21
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"

volumes:
  postgres_data:

